config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :lightning_talks, except:[:destroy]
  get '/auth/github/callback', to: 'authentication#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

  resources :users, only:[:show]

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :lightning_talks
    resources :users, except:[:create, :new]
  end
end

app/models/lightning_talk.rb
class LightningTalk < ActiveRecord::Base
  TIMES = ['4:30PM', '4:35PM','4:40PM', '4:45PM', '4:50PM']


  validates :description, presence: true
  validates :user, presence: true
  validates :date, presence: true
  validates :talk_time, presence: true
  validates_uniqueness_of :date, scope: :talk_time
  validate :must_be_tuesday_or_thursday

  belongs_to :user

  private
  
  def must_be_tuesday_or_thursday
    if date.strftime("%A") != "Tuesday" && date.strftime("%A") != "Thursday"
      errors[:base]  << "Date must be on Tuesday or Thursday"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, presence: true, uniqueness: true
  has_many :lightning_talks
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

  def index
  end

end

app/controllers/admin/lightning_talks_controller.rb
class Admin::LightningTalksController < ApplicationController
  before_action :set_lightning_talk, only:[:show, :edit, :update]
  before_action :check_for_admin

  def index
    lightning_talks = LightningTalk.all
    @lightning_talks = lightning_talks.order(date: :asc, talk_time: :asc)
  end

  def show
    @user = User.find(@lightning_talk.user_id)
  end

  def new
    @lightning_talk = LightningTalk.new
  end

  def create
    @lightning_talk = LightningTalk.new(lightning_talk_params)
    if @lightning_talk
      flash[:notice] = "You have successfully created a lightning talk"
      redirect_to admin_lightning_talks_path
    else
      render :new
    end
  end


  def edit
  end

  def update
    if @lightning_talk.update(lightning_talk_params)
      flash[:notice] = 'You have updated your lightning talk'
      redirect_to admin_lightning_talks_path
    else
      render :edit
    end
  end

  def destroy
    LightningTalk.find(params[:id]).destroy
    flash[:notice] = 'You are too scared to give a lightning talk?'
    redirect_to admin_lightning_talks_path
  end

  private

  def lightning_talk_params
    params.require(:lightning_talk).permit(:user, :description, :date)
  end

  def set_lightning_talk
    @lightning_talk = LightningTalk.find(params[:id])
  end

  def check_for_admin
    unless current_user && current_user.admin
      flash[:notice] = "You do not have permission"
      redirect_to root_path
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :ensure_current_user

  def ensure_current_user
    redirect_to '/auth/github' unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  skip_before_action :ensure_current_user

  def new
    @user = User.new
  end

  def create
    email = request.env['omniauth.auth']['info']['email']
    name = request.env['omniauth.auth']['info']['name']
    auth_token = request.env['omniauth.auth']['credentials']['token']
    user = User.find_or_create_by(email: email, name: name)
    if user.present?
      session[:user_id] = user.id
      flash[:notice] = "Thanks for logging in #{user.name}"
      redirect_to lightning_talks_path
    else
      flash[:notice] = "Something went wrong"
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/lightning_talks_controller.rb
class LightningTalksController < ApplicationController
  before_action :set_lightning_talk, only:[:show, :edit, :update]

  def index
    lightning_talks = LightningTalk.all
    @lightning_talks = lightning_talks.order(date: :asc, talk_time: :asc)
    @completed_talks = lightning_talks.where()
  end

  def show
    @user = User.find(@lightning_talk.user_id)
  end

  def new
    @lightning_talk = LightningTalk.new
  end

  def create
    @lightning_talk = LightningTalk.new(lightning_talk_params)
    @lightning_talk.user_id = current_user.id
    if @lightning_talk.save
      flash[:notice] = 'You have signed up for a new lightning talk'
      redirect_to lightning_talk_path(@lightning_talk)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @lightning_talk.update(lightning_talk_params)
      flash[:notice] = 'You have updated your lightning talk'
      redirect_to lightning_talk_path(@lightning_talk)
    else
      render :edit
    end
  end

  private

  def lightning_talk_params
    params.require(:lightning_talk).permit(:user, :description, :date, :talk_time)
  end

  def set_lightning_talk
    @lightning_talk = LightningTalk.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :ensure_current_user
  def index
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/index.html.haml
%h1 Administration
%ul
  %li= link_to 'Manage Talks', admin_lightning_talks_path

app/views/admin/lightning_talks/_form.haml
= render partial: "shared/errors", locals: {object: @lightning_talk}

= form_for @lightning_talk, url: admin_lightning_talk_path(@lightning_talk), html: {class: "form-horizontal"} do |f|
  .form-group
    = f.label :description, class: 'control-label col-md-2'
    .col-md-4
      = f.text_field :description, class: 'form-control'
  .form-group
    = f.label :date, class: 'control-label col-md-2'
    .col-md-4
      = f.date_field :date, class: 'form-control'
  .form-group
    = f.label :talk_time, class: 'control-label col-md-2'
    .col-md-4
      = f.collection_select :talk_time, LightningTalk::TIMES, :to_s, :to_s, {}, class: 'form-control'
  .form-group
    .col-md-6.col-md-offset-2
      = f.submit class:'btn btn-primary'
      = link_to 'Back', admin_lightning_talks_path, class: 'btn btn-default'

app/views/admin/lightning_talks/edit.haml
.page_header  
  %h1 Edit Lightning Talk
= render 'form'

app/views/admin/lightning_talks/index.haml
.page-header
  %h1 Admin: Upcoming Talks
%table.table
  %thead
    %tr
      %th User
      %th Description
      %th Time
      %th{colspan: 2} Date
  %tbody
    - @lightning_talks.each do |talk|
      %tr
        %td= link_to talk.user.name, admin_lightning_talk_path(talk)
        %td= talk.description
        %td= talk.talk_time.strftime('%l:%M %p')
        %td= talk.date.strftime("%A %m/%d")
        %td.text-right
          = link_to 'Edit', edit_admin_lightning_talk_path(talk), class:"btn btn-primary"
          = link_to 'Delete', admin_lightning_talk_path(talk), method: :delete, data:{confirm: 'Giving up?'}, class:"btn btn-danger"

app/views/admin/lightning_talks/new.haml
.page_header
  %h1 New Lightning Talk
= render partial: "shared/errors", locals: {object: @lightning_talk}
= form_for @lightning_talk, url: admin_lightning_talks_path, html: {class: "form-horizontal"} do |f|
  -# .form-group
  -#   = f.label :user_id,"User", class: 'control-label col-md-2'
  -#   .col-md-4
  -#     = f.collection_select :talk_time, LightningTalk::Users, :to_s, :to_s, {}, class: 'form-control'
  .form-group
    = f.label :description, class: 'control-label col-md-2'
    .col-md-4
      = f.text_field :description, class: 'form-control'
  .form-group
    = f.label :date, class: 'control-label col-md-2'
    .col-md-4
      = f.date_field :date, class: 'form-control'
  .form-group
    = f.label :talk_time, class: 'control-label col-md-2'
    .col-md-4
      = f.collection_select :talk_time, LightningTalk::TIMES, :to_s, :to_s, {}, class: 'form-control'
  .form-group
    .col-md-6.col-md-offset-2
      = f.submit class:'btn btn-primary'
      = link_to 'Back', admin_lightning_talks_path, class: 'btn btn-default'

app/views/admin/lightning_talks/show.haml
.page-header
  .pull-right
    = link_to 'Index', admin_lightning_talks_path, class: 'btn btn-info'
  %h1= @user.name
%table.table
  %thead
    %tr
      %th Description
      %th Time
      %th{colspan: 3} Date
  %tbody
    - @user.lightning_talks.each do |talk|
      %tr
        %td= talk.description
        %td= talk.talk_time.strftime('%l:%M %p')
        %td= talk.date.strftime("%A %m/%d")
        %td.text-right
          = link_to 'Edit', edit_admin_lightning_talk_path(talk), class:"btn btn-primary"
          = link_to 'Delete', admin_lightning_talk_path(talk), class: "btn btn-danger", method: :delete, data:{confirm: "Are you sure?"}

app/views/authentication/new.haml
= form_for @user, url: signin_path, html: { class: "signin-form" } do |f|
  .div
    = f.label :email, autofocus: true
    = f.email_field :email
  .div
    = f.label :password
    = f.password_field :password
  .div
    = f.submit "Login"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LightningTalkApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      %nav.navbar.navbar-fixed-top.navbar-inverse
        .container
          = link_to "g7 Lightning Talks", lightning_talks_path, id: "logo"
          - if current_user && current_user.admin
            .pull-right
              = link_to "Logout", signout_path, class: 'navbar-btn btn btn-danger'
              = link_to "Admin", admin_path, class: 'navbar-btn btn btn-danger'
          - elsif current_user
            .pull-right
              = link_to "Logout", signout_path, class: 'navbar-btn btn btn-danger'
          - else
            .pull-right
              = link_to "Login", '/auth/github', class: 'navbar-btn btn btn-danger'
    .container
      - if flash[:notice]
        .alert.alert-success
          = flash[:notice]
      = yield
    %footer
      .container
        .page-header

app/views/lightning_talks/_form.haml
= render partial: "shared/errors", locals: {object: @lightning_talk}

= form_for @lightning_talk, html: {class: "form-horizontal"} do |f|
  .form-group
    = f.label :description, class: 'control-label col-md-2'
    .col-md-4
      = f.text_field :description, class: 'form-control'
  .form-group
    = f.label :date, class: 'control-label col-md-2'
    .col-md-4
      = f.date_field :date, class: 'form-control'
  .form-group
    = f.label :talk_time, class: 'control-label col-md-2'
    .col-md-4
      = f.collection_select :talk_time, LightningTalk::TIMES, :to_s, :to_s, {}, class: 'form-control'
  .form-group
    .col-md-6.col-md-offset-2
      = f.submit class:'btn btn-primary'
      = link_to 'Back', lightning_talks_path, class: 'btn btn-default'

app/views/lightning_talks/edit.haml
.page-header
  %h1 Edit Lightning Talk
= render 'form'

app/views/lightning_talks/index.haml
.page-header
  .pull-right
    = link_to 'New Lightning Talk', new_lightning_talk_path, class:"btn btn-info"
  %h1 Upcoming Talks
%table.table
  %thead
    %tr
      %th User
      %th Description
      %th Time
      %th{colspan: 3} Date
  %tbody
    - @lightning_talks.each do |talk|
      %tr
        %td= link_to talk.user.name, user_path(talk.user_id)
        %td= talk.description
        %td= talk.talk_time.strftime('%l:%M %p')
        %td= talk.date.strftime("%A %m/%d")

app/views/lightning_talks/new.haml
.page-header
  %h1 New Lightning Talk
= render 'lightning_talks/form'

app/views/lightning_talks/show.haml
.page-header
  .pull-right
    = link_to 'Index', lightning_talks_path, class: 'btn btn-info'
  %h1= @user.name
%table.table
  %thead
    %tr
      %th Description
      %th Time
      %th{colspan: 3} Date
  %tbody
    - @user.lightning_talks.each do |talk|
      %tr
        %td= talk.description
        %td= talk.talk_time.strftime('%l:%M %p')
        %td= talk.date.strftime("%A %m/%d")
        %td.text-right
          = link_to 'Edit', edit_lightning_talk_path(talk), class:"btn btn-primary"

app/views/shared/_errors.haml
- if object.errors.any?
  .row
    .col-md-7.col-md-offset-2
      .alert.alert-danger
        %h3
          = pluralize(object.errors.count, "error")
          prohibited this form from being saved:
        - object.errors.full_messages.each do |message|
          %ul
            %li= message

app/views/users/show.haml
.page-header
  %h1= @user.name

%table.table
  %thead
    %tr
      %th Description
      %th Time
      %th date
  %tbody
    - @user.lightning_talks.each do |talk|
      %tr
        %td= talk.description
        %td= talk.talk_time.strftime('%l:%M %p')
        %td= talk.date.strftime("%A %m/%d")

app/views/welcome/index.haml
.page-header
  %h1.text-center Welcome
= image_tag 'Lightning.jpg', class: 'img-responsive'